#!/usr/bin/env ruby
#================================================================================================================================
# RCC
# Copyright 2007-2008 Chris Poirier (cpoirier@gmail.com)
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the 
# License.  You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" 
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the License for the specific language 
# governing permissions and limitations under the License.
#================================================================================================================================
#
#  === DO NOT EDIT THIS FILE! ===
# 
#  It was GENERATED by rcc on %%GENERATION_DATE%%
#     from grammar "%%GRAMMAR_NAME%%"
#
#================================================================================================================================


require "#{File.dirname(File.expand_path(__FILE__))}/common.rb" 
require "#{File.dirname(File.expand_path(__FILE__))}/node.rb" 


%%MODULE_HEADER%%
 


 #============================================================================================================================
 # class Parser
 #  - not much I can say here . . . 

   class %%GRAMMAR_CLASS_NAME%%Parser
      include Common
      
      
    #---------------------------------------------------------------------------------------------------------------------
    # Initialization and public interface
    #---------------------------------------------------------------------------------------------------------------------







    #---------------------------------------------------------------------------------------------------------------------
    # States
    #---------------------------------------------------------------------------------------------------------------------
    
    protected    
    
      %%STATES%%
    
    
       
    

    #---------------------------------------------------------------------------------------------------------------------
    # Productions
    #---------------------------------------------------------------------------------------------------------------------
    
    protected    
    
      %%PRODUCTIONS%%




    
    #---------------------------------------------------------------------------------------------------------------------
    # Support code
    #---------------------------------------------------------------------------------------------------------------------
    
    protected
    
      
   end # %%GRAMMAR_CLASS_NAME%%Parser
   

%%MODULE_FOOTER%%
