#!/usr/bin/env ruby
#================================================================================================================================
#
# Ruby Compiler Compiler (rcc)
#
# Copyright 2007 Chris Poirier (cpoirier@gmail.com)
# Licensed under the Academic Free License version 2.1
#
#================================================================================================================================
#
#  === DO NOT EDIT THIS FILE! ===
# 
#  It was GENERATED by rcc on %%GENERATION_DATE%%
#     from grammar "%%GRAMMAR_NAME%%"
#
#================================================================================================================================


require "#{File.dirname(__FILE__)}/common.rb" 
require "#{File.dirname(__FILE__)}/node.rb" 


%%MODULE_HEADER%%
 


 #============================================================================================================================
 # class Parser
 #  - not much I can say here . . . 

   class %%GRAMMAR_CLASS_NAME%%Parser
      include Common
      
      
      class State
         attr_reader :actions
      end
      
      class Production
         attr_reader :name
         attr_reader :name_number
         attr_reader :node_type
         attr_reader :symbol_count
         attr_reader :slot_mappings
         attr_reader :asn_class
         attr_reader :processor_name
         
         def initialize( name, name_number, node_type, symbol_count, slot_mappings, asn_class )
            @name           = name
            @name_number    = name_number
            @node_type      = node_type
            @symbol_name    = symbol_name
            @slot_mappings  = slot_mappings
            @asn_class      = asn_class
            
            @processor_name = "process_#{@name}"
         end
         
         def enslot_nodes( nodes )
            slots = {}
            @slot_mappings.each do |index, name|
               slots[name] = nodes[index]
            end
            return slots
         end
      end
      

    #---------------------------------------------------------------------------------------------------------------------
    # Initialization and public interface
    #---------------------------------------------------------------------------------------------------------------------
    
    
      #
      # initialize()
   
      def initialize()
         @node_stack  = []
         @state_stack = []
      end
      





    #---------------------------------------------------------------------------------------------------------------------
    # Internal machinery
    #---------------------------------------------------------------------------------------------------------------------
    
    protected    
    

      #
      # reduce_by()
      #  - reduces nodes from the stack to a new node, using a Production
      #  - returns the new Node
      
      def reduce_by( production )
         produced_node = nodes = nil
         
         #
         # First up, pop off the requisite number of objects from the node stack.  We also discard the same number of items 
         # from the other stacks.  Note that, for production purposes, we want the nodes in oldest-to-newest order. 
         
         nodes = @node_stack.slice!(  -production.symbol_count..-1  )
                 @state_stack.slice!( -production.symbol_count..-1  )
         
         #
         # Build the production Node.
         
         produced_node = production.asn_class.new( production.enslot_nodes(nodes) )
         
         #
         # If the user has defined a processor for this ASN, call it.
         
         if method_defined?(production.processor_name) then
            send( production.processor_name, produced_node )
         end
         
         #
         # Return the produced Node.
         
         return produced_node
      end






    #---------------------------------------------------------------------------------------------------------------------
    # States
    #---------------------------------------------------------------------------------------------------------------------
    
    protected    
    
      %%STATES%%
    
    
    
    
    
    #---------------------------------------------------------------------------------------------------------------------
    # Productions
    #---------------------------------------------------------------------------------------------------------------------
    
    protected    
    
      %%PRODUCTIONS%%




    
    #---------------------------------------------------------------------------------------------------------------------
    # Support code
    #---------------------------------------------------------------------------------------------------------------------
    
    protected
    
      
   end # %%GRAMMAR_CLASS_NAME%%Parser
   

%%MODULE_FOOTER%%
